x-image: &production-image
  image: ${APP_IMAGE:-mpratamamail/removebgku:latest}
  build: null
  pull_policy: always

services:
  web:
    <<: *production-image
  worker:
    <<: *production-image
  beat:
    <<: *production-image
