# Generated by Django 5.2.16 on 2026-07-22 14:59

import apps.jobs.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_identifier', models.CharField(db_index=True, max_length=255)),
                ('client_ip_hash', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_view_audit_log', 'Dapat melihat audit log')],
            },
        ),
        migrations.CreateModel(
            name='ImageJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Menunggu antrean'), ('processing', 'Sedang diproses'), ('succeeded', 'Selesai'), ('failed', 'Gagal'), ('canceled', 'Dibatalkan'), ('expired', 'Kedaluwarsa'), ('files_deleted', 'File dihapus')], db_index=True, default='queued', max_length=20)),
                ('original_file', models.FileField(max_length=500, upload_to=apps.jobs.models.original_upload_path)),
                ('result_file', models.FileField(blank=True, max_length=500, upload_to=apps.jobs.models.result_upload_path)),
                ('thumbnail_file', models.FileField(blank=True, max_length=500, upload_to=apps.jobs.models.thumbnail_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('safe_download_filename', models.CharField(max_length=255)),
                ('original_mime_type', models.CharField(max_length=80)),
                ('result_mime_type', models.CharField(blank=True, max_length=80)),
                ('original_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('result_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('original_width', models.PositiveIntegerField(default=0)),
                ('original_height', models.PositiveIntegerField(default=0)),
                ('result_width', models.PositiveIntegerField(default=0)),
                ('result_height', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(db_index=True, max_length=80)),
                ('session_owner_hash', models.CharField(db_index=True, max_length=64)),
                ('client_ip_hash', models.CharField(max_length=64)),
                ('user_agent_truncated', models.CharField(blank=True, max_length=255)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message_public', models.CharField(blank=True, max_length=500)),
                ('error_message_internal', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('files_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('processing_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('original_sha256', models.CharField(max_length=64)),
                ('result_sha256', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_view_internal_errors', 'Dapat melihat error internal'), ('can_retry_job', 'Dapat mencoba ulang job'), ('can_cancel_job', 'Dapat membatalkan job'), ('can_delete_job_files', 'Dapat menghapus file job')],
                'indexes': [models.Index(fields=['status', 'created_at'], name='jobs_status_created_idx'), models.Index(fields=['session_owner_hash', 'created_at'], name='jobs_owner_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'succeeded')), models.Q(('status', 'succeeded'), _negated=True), _connector='OR'), name='succeeded_has_completed_at'), models.CheckConstraint(condition=models.Q(models.Q(('failed_at__isnull', False), ('status', 'failed')), models.Q(('status', 'failed'), _negated=True), _connector='OR'), name='failed_has_failed_at')],
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('message', models.CharField(max_length=500)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.imagejob')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='HapusBackground', max_length=100)),
                ('site_tagline', models.CharField(default='Hapus latar belakang gambar dengan mudah', max_length=255)),
                ('public_upload_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.CharField(default='Kami sedang melakukan pemeliharaan singkat.', max_length=500)),
                ('default_model', models.CharField(default='u2netp', max_length=80)),
                ('allowed_models', models.JSONField(blank=True, default=list)),
                ('upload_max_bytes', models.PositiveIntegerField(default=10485760)),
                ('max_image_pixels', models.PositiveIntegerField(default=36000000)),
                ('retention_hours', models.PositiveIntegerField(default=24)),
                ('max_active_jobs_per_session', models.PositiveSmallIntegerField(default=3)),
                ('max_queue_size', models.PositiveSmallIntegerField(default=50)),
                ('upload_rate_limit_per_hour', models.PositiveSmallIntegerField(default=10)),
                ('show_public_history', models.BooleanField(default=True)),
                ('privacy_notice', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'konfigurasi situs',
                'verbose_name_plural': 'konfigurasi situs',
                'permissions': [('can_manage_site_configuration', 'Dapat mengelola konfigurasi situs')],
            },
        ),
    ]
