# Generated by Django 5.2.16 on 2026-07-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="site_name",
            field=models.CharField(default="REMOVEBGKU", max_length=100),
        ),
    ]
