# Generated by Django 5.2.16 on 2026-07-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_siteconfiguration_site_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="upload_max_bytes",
            field=models.PositiveIntegerField(default=52428800),
        ),
    ]
